export const WALKING_EVENTS = Object.freeze([
  Object.freeze({
    id: 'sunrise-corniche-loop',
    title: 'Sunrise Corniche Loop',
    location: 'Abu Dhabi Corniche',
    date: '2026-10-09',
    time: '06:15',
    durationMinutes: 75,
    distanceKm: 5.2,
    difficulty: 'easy',
    description:
      'A calm waterfront walk for people who want low-pressure conversation before the day gets busy.',
    route: Object.freeze([
      'Corniche East Plaza',
      'Family Park Promenade',
      'Heritage Fountain',
      'Corniche East Plaza',
    ]),
    food: Object.freeze({
      available: true,
      note: 'Coffee and dates at the finish point.',
    }),
    signUp: Object.freeze({
      capacity: 18,
      remaining: 7,
      deadline: '2026-10-08T18:00:00+04:00',
    }),
    map: Object.freeze({
      latitude: 24.4748,
      longitude: 54.3377,
      label: 'Abu Dhabi Corniche East Plaza',
    }),
    imageTheme: 'sunrise waterfront promenade',
    tags: Object.freeze(['waterfront', 'morning', 'social']),
  }),
  Object.freeze({
    id: 'mangrove-wellbeing-walk',
    title: 'Mangrove Wellbeing Walk',
    location: 'Jubail Mangrove Park',
    date: '2026-10-12',
    time: '17:30',
    durationMinutes: 90,
    distanceKm: 4.1,
    difficulty: 'easy',
    description:
      'A quiet boardwalk route for students and young professionals looking to reset after class or work.',
    route: Object.freeze([
      'Visitor Center',
      'West Boardwalk',
      'Observation Deck',
      'Visitor Center',
    ]),
    food: Object.freeze({
      available: false,
      note: 'Bring water; snacks are available near the visitor center.',
    }),
    signUp: Object.freeze({
      capacity: 14,
      remaining: 3,
      deadline: '2026-10-11T20:00:00+04:00',
    }),
    map: Object.freeze({
      latitude: 24.5432,
      longitude: 54.4386,
      label: 'Jubail Mangrove Park Visitor Center',
    }),
    imageTheme: 'mangrove boardwalk golden hour',
    tags: Object.freeze(['nature', 'evening', 'mindful']),
  }),
  Object.freeze({
    id: 'campus-step-club',
    title: 'Campus Step Club',
    location: 'MBZUAI Campus',
    date: '2026-10-15',
    time: '19:00',
    durationMinutes: 60,
    distanceKm: 3,
    difficulty: 'easy',
    description:
      'A beginner-friendly loop designed for people who want accountability without a competitive fitness vibe.',
    route: Object.freeze([
      'Main Entrance',
      'Library Walkway',
      'Residence Loop',
      'Main Entrance',
    ]),
    food: Object.freeze({
      available: true,
      note: 'Light sandwiches after the walk.',
    }),
    signUp: Object.freeze({
      capacity: 20,
      remaining: 12,
      deadline: '2026-10-15T12:00:00+04:00',
    }),
    map: Object.freeze({
      latitude: 24.4339,
      longitude: 54.6173,
      label: 'MBZUAI Main Entrance',
    }),
    imageTheme: 'modern university campus evening',
    tags: Object.freeze(['campus', 'beginner', 'community']),
  }),
  Object.freeze({
    id: 'galleria-indoor-steps',
    title: 'Galleria Indoor Steps',
    location: 'The Galleria, Al Maryah Island',
    date: '2026-10-16',
    time: '18:30',
    durationMinutes: 50,
    distanceKm: 3.4,
    difficulty: 'easy',
    description:
      'An air-conditioned after-work circuit for people who want a convenient social walk near shops and cafes.',
    route: Object.freeze([
      'North Atrium',
      'Waterfront Link',
      'South Atrium',
      'North Atrium',
    ]),
    food: Object.freeze({
      available: true,
      note: 'Water refill point and cafe options at the finish.',
    }),
    signUp: Object.freeze({
      capacity: 20,
      remaining: 9,
      deadline: '2026-10-16T12:00:00+04:00',
    }),
    map: Object.freeze({
      latitude: 24.5018,
      longitude: 54.3884,
      label: 'The Galleria North Atrium',
    }),
    imageTheme: 'bright modern indoor mall walking circuit',
    tags: Object.freeze(['after-work', 'indoor', 'mall', 'social']),
  }),
  Object.freeze({
    id: 'yas-park-power-walk',
    title: 'Yas Park Power Walk',
    location: 'Yas Gateway Park',
    date: '2026-10-18',
    time: '07:00',
    durationMinutes: 105,
    distanceKm: 7.4,
    difficulty: 'hard',
    description:
      'A brisk weekend walk with longer stretches for people who want a little challenge and a reliable group.',
    route: Object.freeze([
      'North Car Park',
      'Shaded Track',
      'Lake View Path',
      'North Car Park',
    ]),
    food: Object.freeze({
      available: true,
      note: 'Breakfast wraps available after the route.',
    }),
    signUp: Object.freeze({
      capacity: 16,
      remaining: 5,
      deadline: '2026-10-17T18:00:00+04:00',
    }),
    map: Object.freeze({
      latitude: 24.4957,
      longitude: 54.6075,
      label: 'Yas Gateway Park North Car Park',
    }),
    imageTheme: 'green urban park fitness trail',
    tags: Object.freeze(['fitness', 'weekend', 'brisk']),
  }),
]);
